// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDw-JtwGK6oAxKO5EhKfyrQusz4RiRwGLM',
    appId: '1:494991867882:web:58a2eca469fddaa8aa7c93',
    messagingSenderId: '494991867882',
    projectId: 'covidtracker-5bdfe',
    authDomain: 'covidtracker-5bdfe.firebaseapp.com',
    storageBucket: 'covidtracker-5bdfe.appspot.com',
    measurementId: 'G-D21J2YM85F',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDeacM7Pns7dP5iIMhUFMaH7-E1mHiG2ls',
    appId: '1:494991867882:android:60be3cf568c129c4aa7c93',
    messagingSenderId: '494991867882',
    projectId: 'covidtracker-5bdfe',
    storageBucket: 'covidtracker-5bdfe.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDgS8_y-YjsdZbsJ7f5J17aS3a8aLnLNck',
    appId: '1:494991867882:ios:4300e734e0a040fbaa7c93',
    messagingSenderId: '494991867882',
    projectId: 'covidtracker-5bdfe',
    storageBucket: 'covidtracker-5bdfe.appspot.com',
    iosBundleId: 'com.fnine.lab12CovidTracker',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDgS8_y-YjsdZbsJ7f5J17aS3a8aLnLNck',
    appId: '1:494991867882:ios:4300e734e0a040fbaa7c93',
    messagingSenderId: '494991867882',
    projectId: 'covidtracker-5bdfe',
    storageBucket: 'covidtracker-5bdfe.appspot.com',
    iosBundleId: 'com.fnine.lab12CovidTracker',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDw-JtwGK6oAxKO5EhKfyrQusz4RiRwGLM',
    appId: '1:494991867882:web:5f686f8398017786aa7c93',
    messagingSenderId: '494991867882',
    projectId: 'covidtracker-5bdfe',
    authDomain: 'covidtracker-5bdfe.firebaseapp.com',
    storageBucket: 'covidtracker-5bdfe.appspot.com',
    measurementId: 'G-1GXPRWGDE1',
  );
}
